package it.northleap.backend.entities;

// Porting 1:1 dell'enum FieldType originale (schema.prisma di crm_geck) — ~35-37 tipi possibili
public enum FieldType {
    TEXT,
    VARCHAR,
    LONGTEXT,
    RICHTEXT,
    NUMBER,
    INTEGER,
    BIGINT,
    DECIMAL,
    FLOAT,
    PERCENT,
    CURRENCY,
    RATING,
    DURATION,
    DATE,
    DATETIME,
    TIME,
    TIMESTAMP,
    BOOLEAN,
    SELECT,
    MULTISELECT,
    TAGS,
    EMAIL,
    PHONE,
    URL,
    COLOR,
    ICON,
    ADDRESS,
    GEO,
    JSON,
    UUID,
    AUTONUMBER,
    RELATION,
    FILE,
    IMAGE,
    FORMULA,
    ROLLUP,
    LOOKUP,
    USER,
    STATUS
}
