import {
  Activity,
  Award,
  Banknote,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Camera,
  Car,
  Clipboard,
  Clock,
  Coffee,
  Compass,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Factory,
  File,
  FilePen,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderKanban,
  Gem,
  Gift,
  Globe,
  Handshake,
  Heart,
  Image as ImageIcon,
  Inbox,
  Key,
  Layers,
  LifeBuoy,
  Lightbulb,
  Link,
  Lock,
  type LucideIconData,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Music,
  Navigation,
  Package,
  Phone,
  Pin,
  Plane,
  Receipt,
  Repeat,
  Rocket,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  Smile,
  SquareCheckBig,
  Star,
  Store,
  Tag,
  Tags,
  Target,
  ThumbsUp,
  Ticket,
  TrendingUp,
  Trophy,
  Truck,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wrench,
  Zap
} from 'lucide-angular';

// Mappa la stringa `ObjectType.icon`/`FieldDef.icon` (kebab-case, nomi di icone lucide) al
// componente lucide corrispondente. PER AGGIUNGERE/CAMBIARE un'icona: aggiungi una riga qui sotto
// (chiave = nome kebab-case lucide) e importa il componente in cima. Nomi e anteprime su
// https://lucide.dev/icons. Se una chiave non e' mappata, ricade su Box.
//
// Nota: alcuni nomi lucide cambiano tra versioni - es. il backend semina `check-square` ma in
// questa versione di lucide-angular si chiama SquareCheckBig; `file-signature` non esiste piu' e
// usiamo FilePen come sostituto piu' vicino. Per questo i nuovi nomi qui sotto sono stati
// verificati uno a uno contro i `export` effettivi del pacchetto installato.
const ICONS: Record<string, LucideIconData> = {
  // set storico (chiavi seminate dal backend per i 19 object type di default)
  building: Building,
  user: User,
  target: Target,
  filter: Filter,
  'trending-up': TrendingUp,
  'file-text': FileText,
  box: Box,
  'file-signature': FilePen,
  'folder-kanban': FolderKanban,
  'check-square': SquareCheckBig,
  'life-buoy': LifeBuoy,
  file: File,
  image: ImageIcon,
  'message-circle': MessageCircle,
  calendar: Calendar,
  repeat: Repeat,
  receipt: Receipt,
  'credit-card': CreditCard,
  bell: Bell,
  // set ampliato (scelta libera dell'utente nei picker icona)
  activity: Activity,
  award: Award,
  banknote: Banknote,
  bike: Bike,
  'book-open': BookOpen,
  bookmark: Bookmark,
  briefcase: Briefcase,
  'building-2': Building2,
  camera: Camera,
  car: Car,
  clipboard: Clipboard,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  crown: Crown,
  database: Database,
  'dollar-sign': DollarSign,
  factory: Factory,
  flag: Flag,
  folder: Folder,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  inbox: Inbox,
  key: Key,
  layers: Layers,
  lightbulb: Lightbulb,
  link: Link,
  lock: Lock,
  mail: Mail,
  map: MapIcon,
  'map-pin': MapPin,
  megaphone: Megaphone,
  mic: Mic,
  music: Music,
  navigation: Navigation,
  package: Package,
  phone: Phone,
  pin: Pin,
  plane: Plane,
  rocket: Rocket,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shopping-cart': ShoppingCart,
  smile: Smile,
  star: Star,
  store: Store,
  tag: Tag,
  tags: Tags,
  'thumbs-up': ThumbsUp,
  ticket: Ticket,
  trophy: Trophy,
  truck: Truck,
  'user-check': UserCheck,
  users: Users,
  video: Video,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap
};

export function resolveObjectIcon(icon: string | null | undefined): LucideIconData {
  return (icon && ICONS[icon]) || Box;
}

// Chiavi icona selezionabili (per i picker, es. scelta icona di un campo/oggetto). Sono le
// stesse chiavi mappate sopra, così tutto si risolve poi con resolveObjectIcon.
export const ICON_KEYS: string[] = Object.keys(ICONS);
