spring.application.name=backend

app.jwt.jwt_access_secret=${JWT_ACCESS_SECRET}
app.jwt.jwt_refresh_secret=${JWT_REFRESH_SECRET}
app.jwt.expiration-access-ms=900000
app.jwt.expiration-refresh-ms=2592000000
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.datasource.url=jdbc:postgresql://localhost:5432/crm_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect